### ISSUE TITLE
1.9.0.1 incorrectly reported as 1.8.1.0

### ISSUE THREAD

**Issue by gwillem** [steverobbins/magento-version-identification-php#1]
Hi Steve, good work! However I suspect there's a logic error in your code. 
For example, you identify `1.8.1.0` based on `4124f1904f8c3fb40675bbff6268d017 skin/adminhtml/default/default/boxes.css` but newer versions have the same hash.

**Comment by steverobbins** [comment]
Thanks for pointing that out.  I've quick fixed it for now.  Gonna look into making it more accurate again.
