### ISSUE TITLE
Magento ver. 1.8.1.0 defined as 1.9.0.0, 1.9.0.1

### ISSUE THREAD

**Issue by vdrahaniuk** [steverobbins/magento-version-identification-php#6]
Hi) I use your [magescan](https://github.com/steverobbins/magescan).  Magento ver. 1.8.1.0 defined as 1.9.0.0, 1.9.0.1 (4124f1904f8c3fb40675bbff6268d017). Also Magento 1.9.0.0 defined as 1.9.2.0 (ba8dd746c8468bfd1cff5c77eadc71a4). 
In magento-version-identification\src\Mvi\Check.php

```
 public function getInfo()
    {
        $versions = json_decode(
            file_get_contents(dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR . 'version.json'),
            true
        );
        foreach ($versions as $file => $hash) {
            $md5 = md5(@file_get_contents($this->url . $file));
            if (isset($hash[$md5])) {
                return $hash[$md5];
            }
        }
        return false;
    }
```

This function return only first entry $md5 in $hash. File skin/adminhtml/default/default/boxes.css  there is also in 1.8.1.0, but its show 1.9.0.0, 1.9.0.1 . Maybe Its better check all files and get with versions the same for this?

**Comment by steverobbins** [comment]
I'm not sure I understand what you're asking.

The objective is to get close to the real Magento version without excessively crawling the site.  Once a match is found there's no need to keep getting URLs.

**Comment by vdrahaniuk** [comment]
Yes, but 1.8.1.0 and 1.9.0.0 it is not close. It is because function getInfo() checking md5 skin/adminhtml/default/default/boxes.css and return version 1.9.0.0, 1.9.0.1 . If file "js/mage/adminhtml/sales.js" was before "skin/adminhtml/default/default/boxes.css" in version.json the objective would to get more close version magento.

**Comment by steverobbins** [comment]
I see.  Yes, there is an issue that, say, someone upgrades the files in `skin` but forgets about `js` resulting in an invalid detection.  This sounds like a one off use case, not sure why you have a `boxes.css` of a future version.  Noted, but nothing something we will account for at this time.
